.TH MYSTRCPY 3 "September 2026" "libmyutils" "Library Functions"
.SH NAME
mystrcpy \- copy a complete C string
.SH SYNOPSIS
.nf
#include <mystrfunctions.h>

int mystrcpy(char *dest, const char *src);
.fi
.SH DESCRIPTION
.B mystrcpy
copies
.I src
to
.I dest
including its terminating null byte. The caller must provide enough
space in
.I dest
for the entire string and the terminator. Source and destination must
not overlap.
.SH RETURN VALUE
Returns the number of characters copied, excluding the terminating null
byte. Returns -1 if either pointer is NULL.
.SH AUTHOR
Rehaan Nazir <rehaan689nazir@gmail.com>
.SH SEE ALSO
.BR mystrlen (3),
.BR mystrncpy (3),
.BR mystrcat (3)
